version: "3.7"

services:
  search-with-ai:
    image: aliangbaby/search-with-ai
    container_name: search-with-ai
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      # openai key
      - OPENAI_KEY=
      # openai proxy
      - OPENAI_PROXY_URL=
      - SEARXNG_HOSTNAME=http://searxng:8080

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: always
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
